spin_version = "1"
authors = ["bhavani"]
description = "Spin tutorial for a Rust based HTTP server"
name = "spin-server-rust"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-server-rust"
source = "target/wasm32-wasi/release/spin_server_rust.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
